### ISSUE TITLE
fuzzy log highlight matches in preview

### ISSUE THREAD

**Issue by yangkev** [bigH/git-fuzzy#38]
Just found this project and I love it so far!

Is it possible to make the diff preview in `git fuzzy log` highlight matches the same way `git fuzzy diff` does?

**Comment by bigH** [comment]
I've tried on my system and my configuration for both of those uses the same "pager" used by `git` (this can be customized using `GF_PREFERRED_PAGER`). Can you share some screenshots that indicate the problem? It could be related to defaults or your system configuration.

`git-fuzzy` tries to be consistent. If you're viewing a diff of your working copy and some files are new, they'll be rendered using `cat` (or `bat` if you have it installed). If you prefer other highlighters, `git-fuzzy` doesn't support them, but it's probably not too hard to implement them.

PRs are welcome; this is likely something I'll not work on unless other folks want it.

**Comment by bigH** [comment]
I suspect it may be that `git log` is noticing that it's being used in a pipe and turns off colors:
```
export GF_LOG_MENU_PARAMS='--pretty=oneline'
```

If that doesn't work, I can't explain why you're not getting colors. [The git wrapper used internally](https://github.com/bigH/git-fuzzy/blob/c4077ec89c1fa8d74666d8c3c51a483890a6461d/lib/core.sh#L171) sets `-c color.ui=always`.

(same answer as #40 though these may not have the same root cause)
