### ISSUE TITLE
Highlight git logs like in the preview

### ISSUE THREAD

**Issue by Morikko** [bigH/git-fuzzy#40]
For the command `git fuzzy log`, the preview shows the commit history with colors.

![2021-07-23_18-01 git log highlight](https://user-images.githubusercontent.com/7831572/126809703-2915e4be-734c-4272-9791-f28a347bfb96.png)

When I do `git fuzzy log`, the lines are all white. If I run `git log --pretty=oneline --abbrev-commit` directly in my terminal, then I have colors.

How is it possible to keep the colors or to set up them ?

**Comment by bigH** [comment]
I suspect it may be that `git log` is noticing that it's being used in a pipe and turns off colors:
```
export GF_LOG_MENU_PARAMS='--pretty=oneline'
```

If that doesn't work, I can't explain why you're not getting colors. [The git wrapper used internally](https://github.com/bigH/git-fuzzy/blob/c4077ec89c1fa8d74666d8c3c51a483890a6461d/lib/core.sh#L171) sets `-c color.ui=always`.

(same answer as #38 though these may not have the same root cause)

**Comment by Morikko** [comment]
Using `export GF_LOG_MENU_PARAMS='--color=always --abbrev-commit --oneline'` resolves it for me. The `--color=always` part.

I got inspired by this: https://unix.stackexchange.com/a/372000/252146

The doc for `git log` is the same as regarding the parameter `color`. I have no idea of what `color.ui` means.
