### ISSUE TITLE
Add files from folder separately

### ISSUE THREAD

**Issue by Andrei-Aksionov** [bigH/git-fuzzy#47]
Hello

I enjoy using this tool but one thing annoys me (when I run `git fuzzy status`): if there is a new folder with files inside I am not able to:
1. See what's inside this folder
2. Add files separately

Here is a screenshot:
<img width="1117" alt="Screenshot 2022-04-08 at 5 17 31 PM" src="https://user-images.githubusercontent.com/58434077/162454887-2820fd46-52ed-456b-8cab-c964e1144bcb.png">

It would be awesome if this issue is fixed.
Thanks.

**Comment by bigH** [comment]
This is a normal behavior of `git`. If you do `git status --short`, you'll see this. There's an `--intent-to-add` switch for `git add` that will display these files.

**Comment by bigH** [comment]
Additional info about `--intent-to-add` [0].

Generally, `--intent-to-add` seems like obscure functionality for special-cases. Though it solves your problem, it'd cause surprising outcomes for most users of `git-fuzzy`. I can think of 2 ways to implement this and both seem problematic:

1. When adding, use `--intent-to-add` on directories. This is problematic because user will need to now manually add each file in the directory, rather than do it all at once, which was the original behavior.

2. When displaying status, we could run `git add --intent-to-add` on any directories in status, then re-display status. Also problematic because if those files were not meant to be added, the user will need to address this directly.

This interface cannot _completely_ replace git as there's a mountain of great functionality in `git` that simply has no need for a visual interface. For your situation I'd simply run `git add --intent-to-add nvim` and then `git-fuzzy` will show you the contents and allow you to decide what to do.

[0] https://stackoverflow.com/a/24347875
