### ISSUE TITLE
Amend in status

### ISSUE THREAD

**Issue by iloveitaly** [bigH/git-fuzzy#51]
Would be great in `fuzzy status` to have a short cut to `git amend` (I like `commit --amend --reuse-message=HEAD`) the current selection.

**Comment by iloveitaly** [comment]
@bigH I'm happy to add this in if it's something you are cool with

**Comment by bigH** [comment]
@iloveitaly I like this suggestion. I definitely have some use for it. Here's how I'd implement it, though I'm open to different approaches:

1. User selects some file/files
2. User presses key combination for "amend"
3. User selects the commit they squash into (`git fuzzy log` should do just fine), default selection is naturally `HEAD` since it'll be the first item in a git log
4. User presses <enter> and (success) returns to the status screen, (fail) returns to the log screen.

**Comment by iloveitaly** [comment]
I was thinking we could keep it simple and use something like:

```
commit --amend --reuse-message=HEAD
```

and then return right back to the selection screen.

i.e. the use case is you want to amend the staged files to the previous comment.

wdyt?

**Comment by bigH** [comment]
Go ahead with your proposed design!

**Comment by iloveitaly** [comment]
This is done!
