### ISSUE TITLE
Please add man pages

### ISSUE THREAD

**Issue by z0rc** [bigH/git-fuzzy#9]
Git provides comprehensive documentation in man form. Same goes with various external git tools, for example https://github.com/tj/git-extras and https://github.com/arzzen/git-quick-stats.

Please add man page for git-fuzzy too.

**Comment by z0rc** [comment]
Compare:
```
git status --help
<shows man page>
```
```
git fuzzy --help
No manual entry for git-fuzzy
```

**Comment by bigH** [comment]
since the tool is interactive and a shim around other tools, i felt this was not worth the effort.

i'd rather spend my energy giving access to more underlying git functionality.

that being said, most of the subcommands obey the underlying git subcommand interfaces. e.g. `git fuzzy diff [..args]` produces the same effective diff as `git diff [..same args]` just interactive.
